- name: set 2ndry interface vars if needed
  include_vars:
    file: int_GEN34.yml
- name: combine gen34 connection into network_connections
  set_fact:
    network_connections: "{{ network_connections + gen34_connection }}"
- name: install routing rules package
  package:
    name: NetworkManager-config-routing-rules
    state: present
- name: start and enable network manager dispatcher service
  service:
    name: NetworkManager-dispatcher
    state: started
    enabled: yes
- name: set gen34 route table
  lineinfile:
    path: /etc/iproute2/rt_tables
    line: 200 gen34source
- name: create gen34table route
  copy:
    content: "default via {{ source.GEN34_gateway }} table gen34source\n"
    dest: "/etc/sysconfig/network-scripts/route-gen34"
- name: create gen34 source based rule
  copy:
    content: "from {{ source.GEN34 }} table gen34source\n"
    dest: "/etc/sysconfig/network-scripts/rule-gen34"
- name: restart network manager to load routing policy
  service:
    name: NetworkManager
    state: restarted
