- name: empty network connections var
  set_fact:
    network_connections: []

- name: include NONAT interface variables if required
  include_vars:
   file: int_nonat.yml
  when: source.NONAT is defined

- name: combine NONAT connection into network_connections
  set_fact:
    network_connections: "{{ network_connections + nonat_connection }}"
  when: source.NONAT is defined

- debug:
    var: network_connections  

- name:
  include_role:
    name: rhel-system-roles.network

